python/djangoblog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

python/djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.home),
    path('about/', views.about),
]

python/djangoblog/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

python/djangoblog/accounts/models.py
from django.db import models

# Create your models here.

python/djangoblog/posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:5]

python/djangoblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('post_list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('post_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('post_list')

python/djangoblog/djangoblog/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

python/djangoblog/posts/views.py
from django.shortcuts import render
from .models import Post

def post_list(request):
    posts = Post.objects.all().order_by('date')
    return render(request, 'posts/post_list.html', {"posts": posts})

def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_detail.html', {'post': post})

python/djangoblog/posts/templates/posts/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">

    <title>Django Blog</title>
</head>
<body class="container mt-5">
<nav class="mb-3">
    {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary btn-sm" type="submit">Log Out</button>
        </form>
    {% else %}
    <a href="{% url 'accounts:login' %}">
       <button>Login</button>
    </a>
    <a href="{% url 'accounts:signup' %}">
       <button>Signup</button>
    </a>
    {% endif %}
</nav>
{% block content %}

{% endblock content %}
</body>
</html>

python/djangoblog/posts/templates/posts/post_detail.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}

    <div class="card mb-4" style="width: 40rem">
        <img src="{% static 'posts/images/'|add:post.slug|add:'.jpeg' %}" class="card-img-top">
        <div class="card-body">
            <h3 class="card-title">{{ post.title }}</h3>
            <h6 class="card-subtitle mb-2 text-muted">{{ post.slug }}</h6>
            <p class="card-text">{{ post.body }}</p>
        </div>
    </div>

{% endblock content %}

python/djangoblog/posts/templates/posts/post_list.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    {% for post in posts %}
        <div class="card mb-4" style="width: 40rem">
            <img src="{% static 'posts/images/'|add:post.slug|add:'.jpeg' %}" class="card-img-top">
            <div class="card-body">
                <h3 class="card-title">{{ post.title }}</h3>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.slug }}</h6>
                <p class="card-text">{{ post.snippet }}...</p>
                <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Read More</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}